# Simple Linear Regression

As you go along you'll get to know how to import a dataset, set up separate variables for features and target, create a train-test split, fit a basic linear regression model, and calculate R2 score.

The first thing we need to do is to import some relevant libraries.
## Import Liraries

In [1]:
import pandas as pd
import numpy as np

`pandas` is a python library, used for data manipulation and analysis.

`NumPy` is a python library, used to perform mathematical operations mainly using multi-dimensional arrays.

## Import Dataset
We'll be using `Ames_Housing_Sales.csv` Dataset.

The Ames housing dataset examines features of houses sold in Ames during the 2006–10 timeframe. The goal is to use the training data to predict the sale prices of the houses in the testing data.

In [2]:
data = pd.read_csv('../datasets/Ames_Housing_Sales.csv')
data.head() #this returns top 5 rows of the dataset

,1stFlrSF,2ndFlrSF,3SsnPorch,Alley,BedroomAbvGr,BldgType,BsmtCond,BsmtExposure,BsmtFinSF1,BsmtFinSF2,...,ScreenPorch,Street,TotRmsAbvGrd,TotalBsmtSF,Utilities,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold,SalePrice
0,856.0,854.0,0.0,None,3,1Fam,TA,No,706.0,0.0,...,0.0,Pave,8,856.0,AllPub,0.0,2003,2003,2008,208500.0
1,1262.0,0.0,0.0,None,3,1Fam,TA,Gd,978.0,0.0,...,0.0,Pave,6,1262.0,AllPub,298.0,1976,1976,2007,181500.0
2,920.0,866.0,0.0,None,3,1Fam,TA,Mn,486.0,0.0,...,0.0,Pave,6,920.0,AllPub,0.0,2001,2002,2008,223500.0
3,961.0,756.0,0.0,None,3,1Fam,Gd,No,216.0,0.0,...,0.0,Pave,7,756.0,AllPub,0.0,1915,1970,2006,140000.0
4,1145.0,1053.0,0.0,None,4,1Fam,TA,Av,655.0,0.0,...,0.0,Pave,9,1145.0,AllPub,192.0,2000,2000,2008,250000.0

In [3]:
# to see how many entries or observation the dataset contains you can simply print its shape
print(data.shape)

(1379, 80)

In [4]:
# to examine how many features are there of each data type(object, float64, int64)
data.dtypes.value_counts()

object     43
float64    21
int64      16
dtype: int64

The __Ames_Housing_Sales__ dataset contains 43 categorical columns and 37 numerical columns.

In [5]:
# to examine each of the columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1379 entries, 0 to 1378
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   1stFlrSF       1379 non-null   float64
 1   2ndFlrSF       1379 non-null   float64
 2   3SsnPorch      1379 non-null   float64
 3   Alley          1379 non-null   object
 4   BedroomAbvGr   1379 non-null   int64
 5   BldgType       1379 non-null   object
 6   BsmtCond       1379 non-null   object
 7   BsmtExposure   1379 non-null   object
 8   BsmtFinSF1     1379 non-null   float64
 9   BsmtFinSF2     1379 non-null   float64
 10  BsmtFinType1   1379 non-null   object
 11  BsmtFinType2   1379 non-null   object
 12  BsmtFullBath   1379 non-null   int64
 13  BsmtHalfBath   1379 non-null   int64
 14  BsmtQual       1379 non-null   object
 15  BsmtUnfSF      1379 non-null   float64
 16  CentralAir     1379 non-null   object
 17  Condition1     1379 non-null   object
 18  Condition2     1379 non-null   object
 19  Electrical     1379 non-null   object
 20  EnclosedPorch  1379 non-null   float64
 21  ExterCond      1379 non-null   object
 22  ExterQual      1379 non-null   object
 23  Exterior1st    1379 non-null   object
 24  Exterior2nd    1379 non-null   object
 25  Fence          1379 non-null   object
 26  FireplaceQu    1379 non-null   object
 27  Fireplaces     1379 non-null   int64
 28  Foundation     1379 non-null   object
 29  FullBath       1379 non-null   int64
 30  Functional     1379 non-null   object
 31  GarageArea     1379 non-null   float64
 32  GarageCars     1379 non-null   int64
 33  GarageCond     1379 non-null   object
 34  GarageFinish   1379 non-null   object
 35  GarageQual     1379 non-null   object
 36  GarageType     1379 non-null   object
 37  GarageYrBlt    1379 non-null   float64
 38  GrLivArea      1379 non-null   float64
 39  HalfBath       1379 non-null   int64
 40  Heating        1379 non-null   object
 41  HeatingQC      1379 non-null   object
 42  HouseStyle     1379 non-null   object
 43  KitchenAbvGr   1379 non-null   int64
 44  KitchenQual    1379 non-null   object
 45  LandContour    1379 non-null   object
 46  LandSlope      1379 non-null   object
 47  LotArea        1379 non-null   float64
 48  LotConfig      1379 non-null   object
 49  LotFrontage    1379 non-null   float64
 50  LotShape       1379 non-null   object
 51  LowQualFinSF   1379 non-null   float64
 52  MSSubClass     1379 non-null   int64
 53  MSZoning       1379 non-null   object
 54  MasVnrArea     1379 non-null   float64
 55  MasVnrType     1379 non-null   object
 56  MiscFeature    1379 non-null   object
 57  MiscVal        1379 non-null   float64
 58  MoSold         1379 non-null   int64
 59  Neighborhood   1379 non-null   object
 60  OpenPorchSF    1379 non-null   float64
 61  OverallCond    1379 non-null   int64
 62  OverallQual    1379 non-null   int64
 63  PavedDrive     1379 non-null   object
 64  PoolArea       1379 non-null   float64
 65  PoolQC         1379 non-null   object
 66  RoofMatl       1379 non-null   object
 67  RoofStyle      1379 non-null   object
 68  SaleCondition  1379 non-null   object
 69  SaleType       1379 non-null   object
 70  ScreenPorch    1379 non-null   float64
 71  Street         1379 non-null   object
 72  TotRmsAbvGrd   1379 non-null   int64
 73  TotalBsmtSF    1379 non-null   float64
 74  Utilities      1379 non-null   object
 75  WoodDeckSF     1379 non-null   float64
 76  YearBuilt      1379 non-null   int64
 77  YearRemodAdd   1379 non-null   int64
 78  YrSold         1379 non-null   int64
 79  SalePrice      1379 non-null   float64
dtypes: float64(21), int64(16), object(43)
memory usage: 862.0+ KB

In [6]:
# to get the total sum of all missing values
data.isnull().sum().sum()

0

In [7]:
# to get descriptive statistics of the dataset
data.describe()

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BsmtFinSF1,BsmtFinSF2,BsmtFullBath,BsmtHalfBath,BsmtUnfSF,EnclosedPorch,...,OverallQual,PoolArea,ScreenPorch,TotRmsAbvGrd,TotalBsmtSF,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold,SalePrice
count,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,...,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.00000
mean,1177.129804,353.424946,3.609862,2.865120,455.578680,48.102248,0.430747,0.058738,570.765047,21.039159,...,6.187092,2.920957,15.945613,6.552574,1074.445975,97.456853,1972.958666,1985.435098,2007.812183,185479.51124
std,387.014961,439.553171,30.154682,0.783961,459.691379,164.324665,0.514052,0.238285,443.677845,60.535107,...,1.345780,41.335545,57.249593,1.589821,436.371874,126.699192,29.379883,20.444852,1.330221,79023.89060
min,438.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1880.000000,1950.000000,2006.000000,35311.00000
25%,894.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,228.000000,0.000000,...,5.000000,0.000000,0.000000,5.000000,810.000000,0.000000,1955.000000,1968.000000,2007.000000,134000.00000
50%,1098.000000,0.000000,0.000000,3.000000,400.000000,0.000000,0.000000,0.000000,476.000000,0.000000,...,6.000000,0.000000,0.000000,6.000000,1008.000000,0.000000,1976.000000,1994.000000,2008.000000,167500.00000
75%,1414.000000,738.500000,0.000000,3.000000,732.000000,0.000000,1.000000,0.000000,811.000000,0.000000,...,7.000000,0.000000,0.000000,7.000000,1314.000000,171.000000,2001.000000,2004.000000,2009.000000,217750.00000
max,4692.000000,2065.000000,508.000000,6.000000,5644.000000,1474.000000,2.000000,2.000000,2336.000000,552.000000,...,10.000000,738.000000,480.000000,12.000000,6110.000000,857.000000,2010.000000,2010.000000,2010.000000,755000.00000

## Set up separate variables for features and target

But before, as we can fit categorical variables into a regression model, we'll drop them from the data frame.

In [8]:
numeric_mask = data.dtypes == np.object
numeric_cols = data.columns[numeric_mask]
data = data.drop(numeric_cols, axis=1)

In __Ames_Housing_Sales__ dataset, `SalePrice` is our target (dependent) variable.

In [9]:
target_col = "SalePrice"

X = data.drop(target_col, axis=1)
y = data[target_col]

Now that we have feature (X) and target (y) data ready to go, we're nearly ready to fit and evaluate a baseline model using our current feature set. We'll need to create a train/validation split before we fit and score the model.

## Create Train Test Splits

To do so we need to import a method called `train_test_split` from Scikit Learn.

In [10]:
# import train_test_split
from sklearn.model_selection import train_test_split

We’ve splited our data into X and y, now we can pass them into `the train_test_split` function as a parameter along with `test_size`, and this function will return us four variables. They’re `X_train`, `y_train`, `X_test`, and `y_test`.

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # splits train and test in 7:3 ratio

## Fit a basic Linear Regression Model

Import the class containing the regression method from `sklearn.linear_model`.

In [12]:
from sklearn.linear_model import LinearRegression

Create an instance of the class.

In [13]:
LR = LinearRegression()

Fit the instance on the data and then predict the expected value

In [14]:
LR = LR.fit(X_train , y_train)
# Predicting
y_train_pred = LR.predict(X_train) # using train data
y_test_pred = LR.predict(X_test) # using test data

## Calculate R2 Score

The R2 score is a very important metric that is used to evaluate the performance of a regression-based machine learning model.

Import the method `r2_score` from the `sklearn.metrics`.

In [15]:
from sklearn.metrics import r2_score

In [16]:
# calculating r2 score
score_train = r2_score(y_train.values, y_train_pred) # using train data
score_test = r2_score(y_test.values, y_test_pred) # using test data

print("-------------------R2 Scores-----------------")
print("Predicting with train data i.e. on seen data : ", score_train)
print("Predicting with test data i.e. on unseen data : ", score_test)

-------------------R2 Scores-----------------
Predicting with train data i.e. on seen data :  0.8387684736812978
Predicting with test data i.e. on unseen data :  0.6474581398991139